### ISSUE TITLE
I stage

### ISSUE THREAD

**Issue by rusdevops** [IlyaHoloday/Stack#1]
@IlyaHoloday 

- [x] 1. Присутсвуют избыточные коментарии. [здесь](https://github.com/IlyaHoloday/Stack/blob/efb404e3b8f4486fdc9530f90857b9ec9f260cae/include/stack.hpp#L9-L13).
- [x] 2. Присутствует не корректный термин. [здесь](https://github.com/IlyaHoloday/Stack/blob/efb404e3b8f4486fdc9530f90857b9ec9f260cae/include/stack.hpp#L13).
- [ ] 3. Присутствует не оптимальное копирование. [здесь](https://github.com/IlyaHoloday/Stack/blob/efb404e3b8f4486fdc9530f90857b9ec9f260cae/include/stack.hpp#L34-L45).
- [x] 4. Не корректная ссылка на `badge of Travis CI` в файле `README.md`. 
  `ilyaholoday -> IlyaHoloday`

**Comment by IlyaHoloday** [comment]
Использовал семантику move и swap для оптимального копирования
